name: elmisi-com

services:
  elmisi-com:
    build: .
    container_name: elmisi-com
    restart: always
    networks:
      - web_proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elmisi-com.rule=Host(`elmisi.com`)"
      - "traefik.http.routers.elmisi-com.entrypoints=websecure"
      - "traefik.http.routers.elmisi-com.tls.certresolver=letsencrypt"
      - "traefik.http.routers.elmisi-com.middlewares=security-headers@file,gzip@file"
      - "traefik.http.services.elmisi-com.loadbalancer.server.port=80"

networks:
  web_proxy_net:
    external: true
